theme: minima
author: Monadi Rividula Vithanage
email: vithanagemonadi12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am 21 year old university student.I am following Bsc(Hons) degree in Information Technology.
 I am in 3rd year second semester.My leisure time activities are listening to music,play badminton,riding bicycle.

# social links

github_username:  https://github.com/Monadi-Rividula # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
